### ISSUE TITLE
Monaco 0.32 won't work with monaco-vim

### ISSUE THREAD

**Issue by RubenRBS** [brijeshb42/monaco-vim#90]
When trying the new Monaco version, we get
```
ERROR in ./node_modules/monaco-vim/lib/cm_adapter.js 10:28-105
Module not found: Error: Can't resolve 'monaco-editor/esm/vs/editor/common/controller/cursorTypeOperations' in '/home/ruben/coding/godbolt/ce/node_modules/monaco-vim/lib'
 @ ./node_modules/monaco-vim/lib/cm/keymap_vim.js 8:41-65
```

Seems like the new path is now found at `monaco-editor/esm/vs/editor/common/cursor/cursorTypeOperations` which makes the new version work as expected

**Comment by brijeshb42** [comment]
Fixed in `monaco-vim@0.2.0`.

**Comment by RubenRBS** [comment]
Thanks! :)

**Comment by vikyd** [comment]
Problem still exist for me.

- monaco-editor: 0.30.1 (not found `monaco-editor/esm/vs/editor/common/cursor/cursorTypeOperations`)
- monaco-vim: 0.3.3

**Comment by CGNonofr** [comment]
> Problem still exist for me.
> 
> * monaco-editor: 0.30.1 (not found `monaco-editor/esm/vs/editor/common/cursor/cursorTypeOperations`)
> * monaco-vim: 0.3.3
> 
> @brijeshb42

The last version of monaco-editor is the 0.33, and they renamed/moved this file

**Comment by vikyd** [comment]
@CGNonofr 

Yes. Maybe monaco-vim should adapt these differences. 

Waiting...

**Comment by CGNonofr** [comment]
> @CGNonofr
> 
> Yes. Maybe monaco-vim should adapt these differences.
> 
> Waiting...

I don't know it there is a way in that particular case

btw, you can't expect this library to keep infinite backward compatibility with monaco-editor, why would you update monaco-vim without updating monaco-editor?

**Comment by brijeshb42** [comment]
should work with `0.3.4`. `monaco-vim` should now be able to support older monaco versions as well.
